# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CEZLDmatZQeSJIN6St1gV_fu5rBUks3_
"""

from deque_module import Deque
def is_palindrome(s):
  d = Deque()

  for ch in s:
    d.add_back(ch) # добавление элементов строки в список

  while d.size() > 1:
    front = d.remove_front()
    back = d.remove_back()

    if front != back:
      return False

  return True # проверка на палиндром

word_is_palindrome = "шалаш"
print(is_palindrome(word_is_palindrome)) # проверка, является ли палиндром палиндромом; возвращает True
word_is_not_palindrome = "кружок"
print(is_palindrome(word_is_not_palindrome)) # проверка, является ли не палиндром палиндромом; возвращает False
check = str(input())
print(is_palindrome(check)) # проверка, является ли введённая строка палиндромом